# Generated by Django 3.2.16 on 2023-01-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='age',
            field=models.DurationField(default=None),
        ),
    ]
