# Generated by Django 3.2.16 on 2023-01-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_model_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
