# Generated by Django 3.2.16 on 2023-01-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230111_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='age',
        ),
    ]
