# Generated by Django 3.2.16 on 2023-01-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_model_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='conform_password',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='model',
            name='password',
        ),
    ]
